package com.caldi.constants

const val EVENTS_NODE = "events"
const val USER_EVENTS_NODE = "events"
const val USERS_NODE = "users"
const val QUESTIONS_NODE = "questions"
const val EVENT_PROFILE_NODE = "eventProfile"
const val ATTENDEES_NODE = "attendees"
const val ATTENDEES_WITH_PROFILE_NODE = "attendeesWithProfile"
const val MEET_NODE = "meet"
const val POSITIVE_MEET_NODE = "positive"
const val NEGATIVE_MEET_NODE = "negative"
const val USER_CHATS_NODE = "userChats"
const val CHATS_NODE = "chats"
const val ORGANIZER_MESSAGES_NODE = "messages"

const val EVENT_CODE_CHILD = "code"
const val PROFILE_PICTURE_CHILD = "profilePicture"
const val TIMESTAMP_CHILD = "timestamp"
const val NOTIFICATION_TOKEN_CHILD = "notificationToken"